<a href="https://colab.research.google.com/github/RafaelCaballero/BME/blob/main/c%C3%B3digo/proyecto2Soluci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Ejercicios diccionarios y listas

1.- Dada la variable datos con información sobre las 10 provincias más pobladas de España y su número de habitantes, ordenada por número de habitantes obtener:

a) El nombre de la segunda provincia más poblada

b) El número de habitantes de la última ciudad en la lista

c) Incrementar en 5 el número de habitantes de la tercera provincia más poblada

d) Añadir una nueva provincia, ```['Bizkaia', 1162054]```

e) Seleccionar todos los elementos excepto el primero y el último de la lista

In [3]:
datos = [['Madrid', 7058041], ['Barcelona', 5924293],
         ['Valencia', 2730314], ['Alicante', 2008809],
         ['Sevilla', 1969075], ['Málaga',1778275], ['Murcia', 1575171], ['Cádiz',1258881],
         ['Illes Balears',1238812],['Las Palmas',1164130] ]

In [7]:
# Solución
#a
print( datos[1][0]  )
#b
print( datos[-1][1]  )

#c
datos[2][1] = datos[2][1]+5
print(datos[2])

#d
datos.append(['Bizkaia', 1162054])
print(datos)
#e
print(datos[1:-1])

Barcelona
1162054
['Valencia', 2730334]
[['Madrid', 7058041], ['Barcelona', 5924293], ['Valencia', 2730334], ['Alicante', 2008809], ['Sevilla', 1969075], ['Málaga', 1778275], ['Murcia', 1575171], ['Cádiz', 1258881], ['Illes Balears', 1238812], ['Las Palmas', 1164130], ['Bizkaia', 1162054], ['Bizkaia', 1162054], ['Bizkaia', 1162054]]
[['Barcelona', 5924293], ['Valencia', 2730334], ['Alicante', 2008809], ['Sevilla', 1969075], ['Málaga', 1778275], ['Murcia', 1575171], ['Cádiz', 1258881], ['Illes Balears', 1238812], ['Las Palmas', 1164130], ['Bizkaia', 1162054], ['Bizkaia', 1162054], ['Bizkaia', 1162054]]


2.- Dado el siguiente array de numpy ```a```, escribir código para:

a) Usar slicing para obtener los 3 primeros elementos del array

b) Crear un nuevo array ```b``` que sea el resultado de sumar 1 a todos los elementos de ```a```

c) Crear un  nuevo array ```c``` que tenga solo los elementos positivos (>0) de  ```a```

d) Contar el número de elementos positivos de ```a```

e)  Crear un  nuevo array ```d``` donde todos los elementos negativos (<0) de  ```a``` hayan sido reemplazados por 0

f) Seleccionar las posiciones 0,2,3,7 y 11 del array (Nota: se puede usar un array de posiciones en lugar de una sola posición, igual que se usa un array de booleanos en los filtros)



In [16]:
import numpy as np
a = np.random.randint(-100,100,15)
a

array([  69,  -21,  -28,  -73,   70,   92,   -6,   11,   58, -100,  -26,
        -48,  -89,   14,   62])

In [22]:
# Solución
#a 3 primeros elementos
print(a[0:3])
#b
b = a+1
print(b)

#c
filtro = a>0
c = a[filtro]
print(c)

#d
print("d: ",len(c))

#d bis
print("d bis: ",filtro.sum()) # contar 1

#e
a = np.random.randint(-100,100,15)
print("a al principio ",a)
d = a.copy()
filtro = a<0
d[filtro] = 0
print("Ejercicio e. a: ",a)
print("             d: ",d)

#f
print( a[[2,0,3,7,11]])

[-76 -33 -50]
[-75 -32 -49 -50  81 -95  92  -2  60 -63  25 -70  13  32  21]
[80 91 59 24 12 31 20]
d:  7
d bis:  7
a al principio  [ 42  91  -8 -46 -63 -94  14  31   3 -51 -22  -2 -78  25 -43]
Ejercicio e. a:  [ 42  91  -8 -46 -63 -94  14  31   3 -51 -22  -2 -78  25 -43]
             d:  [42 91  0  0  0  0 14 31  3  0  0  0  0 25  0]
[ -8  42 -46  31  -2]


3.- La variable ```datosd```  tiene la misma información sobre provincias y número de habitantes pero en formato diccionario

a) Devolver el número de habitantes de Murcia

b) Incrementar en 10 el número de habitantes de Barcelona

c) Añadir una nueva provincia, ```['Bizkaia', 1162054]```

In [24]:
datos = [['Madrid', 7058041], ['Barcelona', 5924293],
         ['Valencia', 2730314], ['Alicante', 2008809],
         ['Sevilla', 1969075], ['Málaga',1778275], ['Murcia', 1575171], ['Cádiz',1258881],
         ['Illes Balears',1238812],['Las Palmas',1164130] ]
datosd = dict(datos)
datosd

{'Madrid': 7058041,
 'Barcelona': 5924293,
 'Valencia': 2730314,
 'Alicante': 2008809,
 'Sevilla': 1969075,
 'Málaga': 1778275,
 'Murcia': 1575171,
 'Cádiz': 1258881,
 'Illes Balears': 1238812,
 'Las Palmas': 1164130}

In [26]:
# Solución
#a
print(datosd["Murcia"])

#b
datosd["Barcelona"] = datosd["Barcelona"] +10
print(datosd)

#c
datosd["Bizkaia"] = 1162054
print(datosd)


1575171
{'Madrid': 7058041, 'Barcelona': 5924303, 'Valencia': 2730314, 'Alicante': 2008809, 'Sevilla': 1969075, 'Málaga': 1778275, 'Murcia': 1575171, 'Cádiz': 1258881, 'Illes Balears': 1238812, 'Las Palmas': 1164130}
{'Madrid': 7058041, 'Barcelona': 5924303, 'Valencia': 2730314, 'Alicante': 2008809, 'Sevilla': 1969075, 'Málaga': 1778275, 'Murcia': 1575171, 'Cádiz': 1258881, 'Illes Balears': 1238812, 'Las Palmas': 1164130, 'Bizkaia': 1162054}


4.- Consideramos el siguiente código con datos de empleados y queremos

a) Acceder al nombre del primer empleado

b) Acceder al tercer teléfono de la segunda empleada

c) Añadir un campo "letra" a la dirección del primer empleado con valor "B"

In [28]:
empleados = [
    {"nombre": "Bertoldo", "dirección": {"calle": "C/Rosal", "núm.": 10}, "telfs.": [111111, 2222, 3333]},
    {"nombre": "Herminia", "dirección": {"calle": "C/Clavel", "núm.": 14, "letra": "A"}, "telfs.": [111111, 2222, 3333]},
    {"nombre": "Aniceto", "dirección": {"calle": "C/Gardenia", "núm.": 3}, "telfs.": [5611122]},
    {"nombre": "Higinia", "dirección": {"calle": "C/Jazmin", "núm.": 122}, "telfs.": [89897612, 134444, "+49001123"]}
]


In [35]:
# Solución
#a
print(empleados[0]["nombre"])
#b
print(empleados[1]['telfs.'][2])

#c
empleados[0]["dirección"]["letra"] = "C"
print(empleados)

Bertoldo
3333
[{'nombre': 'Bertoldo', 'dirección': {'calle': 'C/Rosal', 'núm.': 10, 'letra': 'C'}, 'telfs.': [111111, 2222, 3333]}, {'nombre': 'Herminia', 'dirección': {'calle': 'C/Clavel', 'núm.': 14, 'letra': 'A'}, 'telfs.': [111111, 2222, 3333]}, {'nombre': 'Aniceto', 'dirección': {'calle': 'C/Gardenia', 'núm.': 3}, 'telfs.': [5611122]}, {'nombre': 'Higinia', 'dirección': {'calle': 'C/Jazmin', 'núm.': 122}, 'telfs.': [89897612, 134444, '+49001123']}]
